frig-js/frig

src/javascripts/frigging_bootstrap/components/select.js

Change _inputHtml from just passing the function to calling it in the
Select Component when the select is rendered out. This allows the merge
props to be the default props of the select.

Change _inputHtml Into Function Call In Select Component

---

dist/frig.js
examples/kitchen-sink/coffeescript/kitchen-sink.coffee

Fix the initial of value for select to use the value in ValueLink  instead of the first value in order to always select what is the Frig form data first before doing to the first item to select.

Fix Initial Select Value To Use ValueLink Value

---

src/javascripts/components/value_linked_select.js

Fix an issue with missing nextProps when calling a valueLink in the Textarea because of a bug introduce by #11 Fix Initial Select Value To Use ValueLink Value.
@SpiritBreaker226

Add Missing nextProps In Textarea

---

src/validations.js

Fix the validation min / max to check for null values in order to validate the value and not have false positives.

Fix Validation Min / Max To Check For Null Values

---

docs/core_components.md

See http://frig-js.github.io/frig/core_components/
The headings for `<Form />`, `<Input />` etc are invisible, because they're being interpreted by Markdown as literal HTML tags.
Fixed by escaping the angle brackets.

Fix docs: tag names were being interpreted as HTML by Markdown

---

webpack.config.coffee

Both `dist/frig.js` and `dist/frig.min.js` are getting minified.
`frigging-bootstrap` does this correctly, copied solution from there.

Fix dist/frig.js also being minified

---

docs/core_components.md
src/components/form_error_list.js

Since the refactor to JSX (0.9.x), `<FormErrorList/>` has not been rendering any errors.
This PR:
* extracts `errors` from `context.frigForm` 
* only considers form-level errors, omits input-level errors (provides `errors['base']` as a prop to the frigging-bootstrap `<ThemedErrorList>`)
* allows user to customize which field contains form-level errors via `baseField` prop (default: `"base"`)
* updates docs
There will also be a corresponding PR for `frigging-bootstrap`.

<FormErrorList/> not displaying any errors

---

src/components/form.js

Provides a better error message (and fails fast) when `<Form/>`'s  `data` or `onChange` props are null or undefined.
Consumers of Frig will have to be sure that the expression they set in `<Form data={...} />` always returns an object. If it returns `undefined` (e.g. on the initial load of an empty form), this error will be thrown.
Also see closed PR #34 for more information about how we could have handled this differently.

<Form/>: Throw if `data` or `onChange` are undefined

---

src/factories.js
src/index.js

For non-JSX users, React component factories must be exported.
This PR exports all existing factories, and adds 2 factories for `Submit` and `FormErrorList`.

Add factories for non-JSX users

---

src/higher_order_components/focusable.js

Fix the Focusable to remove _onFocus() when unmounting for all DOM elements that uses EventTarget in order to remove all _onFocus() from the DOM tree when the user leaves the section.

Fix Focusable To Remove _onFocus() When Unmounting

---

src/components/fieldset.js

Fix the Fieldset Fields to show saved label, on the correct fields. Since correctly the filter is removing an elements, in the Fieldset Field array, that is not modified. Because of this the saved label is only displaying, on the first field, as that will always be only element in the array.

Fix Fieldset Fields To Show Saved On Correct Field

---

circle.yml

Fix running of Coveralls if the pull request is coming from a fork version, of the repo. Because CricleCI blocks custom environment variables from running, if the pull request is coming, from a different repo. This is to prevent a developer from scrapping environment variables when the application runs on CricleCI.

Fix Running Coveralls On Fork Pull Request

---

circle.yml

If webpack build fails, CircleCI job should also fail.

Attempt to build on CircleCI using webpack

---

src/components/fieldset_text.js
src/components/unbound_input.js
src/higher_order_components/delegates_public_functions.js
src/higher_order_components/errors_normalizer.js
src/index.js

- Fix higher order components Error Normalizer & Delegates Public Functions to not display errors when rendering on the Frig Form.
- Fix errors in Fieldset and Unbound Input
- Move the Type Mapping to export default, in Index.js, because to allow the developer to develop components of a theme for each of the types that Frig allows to be rendered.

Fix Form's Higher Order Components and Other Components

---

package.json

Update Package.json for React version ranges also remove fs-extra as it is not being used.

Update Package.json For React Version Ranges

---

package.json
src/higher_order_components/errors_normalizer.js
test/components/input.test.js

This PR:
* Adds devDependency `testdouble` for asserting against callbacks.
* Tests `<Input>`'s `render()` and `_onChange()` functions.
* Omitted from testing:
* Public functions: they are trivial and just pass-through to UnboundInput
* `componentWillUnmount`: requires a React render & re-render (tough), fairly trivial one-liner, and also indirectly tested via `Form`'s tests.

Add input test

---

test/components/input.test.js

#67 failed due to bad linting. After a few bad reverts we figured it out.

Fix linting for #67

---

src/components/unbound_input.js
test/components/input.test.js
test/components/unbound_input.test.js

This PR:
* Removes unused `childContextTypes` from `input.test.js`.
* Adds tests for `<UnboundInput>`, including several WIP/pending tests
Note that `childContextTypes` is actually necessary for this test, because `UnboundInput` is actually an `ErrorNormalizer`-wrapped component. (We can also get around this by using `UnboundInput.originalClass`, which we've done for a few tests.)

Add unbound input test

---

src/components/input.js

Add Ignore code coverage to public functions in Input component because those functions are just returning the results from UnboundInput's public functions so testing those will only be testing the results of functions which are already been tested.

Add Ignore Code Coverage, Public Function In Input

---

package.json
src/higher_order_components/focusable.js
test/higher_order_components/focusable.test.js
test/test_helper.js

Leaving this on a branch until we can figure out http://stackoverflow.com/questions/36727059/getting-real-dom-nodes-from-enzyme-or-testing-non-react-events

Add focusable test

---

package.json
src/components/fieldset.js
test/components/fieldset.test.js
test/components/form.test.js
test/components/input.test.js
test/components/unbound_input.test.js

- Add Test for Fieldset
- Add package cloner for deeper cloning because Object.assign only refer to [How To Copy Objects In Javascript](https://www.webreflection.co.uk/blog/2015/10/06/how-to-copy-objects-in-javascript) for more information
- Add test for React Lifecycle because in Fieldset and Input they use those to add and remove their child components when mounting and unmounting

Add Testing For Fieldset

---

src/type_mapping.js

Fixes Frig's `<Input type="string" />` to output `<input type="text" />`
Currently it outputs `<input type="string">`, but HTML inputs do not support type `string` (it just falls back to text since it's an unrecognized type).

Fix htmlInputType for string

---

package.json

Reverts frig-js/frig#177
Can't merge #177 until airbnb releases a new ruleset with peerDeps for `eslint@3.x`

Revert "Update eslint to version 3.0.1 🚀"

---

package.json

Until `eslint-plugin-react` version 6.0 fixes 
```
Configuration for rule "react/jsx-uses-react" is invalid:  
Value "[object Object]" has more items than allowed.
```
As this blocks updates from `eslint` & `eslint-config-airbnb` since they both need `eslint-plugin-react` package.

Revert "Update eslint to version 3.2.2 🚀"
